// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./prisma/schema/schema.prisma",  // Points to your schema file
  migrations: {
    path: "./prisma/schema/migrations",     // Where migrations will be stored
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
